create table if not exists public.visits (
  id bigint generated by default as identity primary key,
  usuario text not null,
  fuente text not null,
  created_at timestamptz default now()
);

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  nombre text not null,
  precio numeric(10,2) not null default 0,
  descripcion text,
  ubicacion text,
  rating numeric(2,1) default 4.8,
  color text,
  created_at timestamptz default now()
);

insert into public.menu_items (nombre, precio, descripcion, ubicacion, rating, color)
values
  ('Tacos al Pastor', 12.99, 'Preparados con técnica tradicional y ingredientes auténticos.', ' México', 4.9, 'linear-gradient(135deg, #1e3c72 0%, #2a5298 100%)'),
  ('Pizza Napolitana', 15.99, 'Horno de leña y masa madre fermentada 24 horas.', ' Italia', 4.8, 'linear-gradient(135deg, #ff6b35 0%, #f7931e 100%)'),
  ('Sushi Premium', 18.99, 'Arroz sushi y pescado fresco de primera calidad.', 'Japón', 4.7, 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)')
on conflict do nothing;

alter table public.visits enable row level security;
alter table public.menu_items enable row level security;

create policy if not exists "Allow public insert on visits" on public.visits
for insert to anon
with check (true);

create policy if not exists "Allow public select on menu_items" on public.menu_items
for select to anon
using (true);
